name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.300'
    - name: Restore local tools
      run: dotnet tool restore
    - name: Install packages
      run: dotnet paket restore
    - name: Build solution
      run: dotnet build -c Release
    - name: Run unit tests
      run: dotnet test
    - name: Upload Usage example
      uses: actions/upload-artifact@v1
      with:
        name: usageExample
        path: ${{ github.workspace }}/tests/Web/bin/Release/netcoreapp3.1/
  sample-web-container:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.300'
      - name: Download Usage example
        uses: actions/download-artifact@v1
        with:
          name: usageExample
      - name: debug
        run: ls -lah
      - name: debug
        run: ls -lah ./tests
      - name: debug
        run: ls -lah ./tests/Web
      - name: debug
        run: ls -lah ./tests/Web/bin
      - name: debug
        run: ls -lah ./tests/Web/bin/Release
      - name: debug
        run: ls -lah ./tests/Web/bin/Release/netcoreapp3.1
    #   - name: Run usage example
    #     run: dotnet run --project ${{ github.workspace }}/tests/UsageExample/UsageExample.fsproj
