name: Build

on:
  branches:
    - master
  paths:
    - '${{ github.workspace }}/CHANGELOG.md'

env:
  CI: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.300'
    - name: Restore local tools
      run: dotnet tool restore
    - name: Install packages
      run: dotnet paket restore
    - name: Set version from changelog
      run: echo ::set-env name=RELEASE_VERSION::$(dotnet fsi ./updateVersion.fsx)
    - name: Build solution
      run: dotnet build
    - name: Run unit tests
      run: dotnet test
    - name: Start sample web
      run: dotnet  run --project ${{ github.workspace }}/tests/Web/Web.fsproj &
    - name: Run usage example
      run: dotnet run --project ${{ github.workspace }}/tests/UsageExample/UsageExample.fsproj
    - name: Pack nuget package
      run: dotnet pack ./src/Scrutiny/Scrutiny.fsproj --include-source --include-symbols --output ${{ github.workspace }}/output
    - name: Push nuget package
      run: dotnet nuget push ${{ github.workspace }}/output/Scrutiny.*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGETAPI }}
    - uses: hole19/git-tag-action@master
      env:
        TAG: ${{ env.RELEASE_VERSION }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
